# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cflcli < Formula
  desc "Confluence CLI for managing pages with local Markdown files"
  homepage "https://github.com/takymt/cflcli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takymt/cflcli/releases/download/v0.2.1/cfl_0.2.1_darwin_amd64.tar.gz"
      sha256 "ac9c70c3cb3ba53165e127d055de5ddefc90a093c9804986b8f08c7ac45bb729"

      def install
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takymt/cflcli/releases/download/v0.2.1/cfl_0.2.1_darwin_arm64.tar.gz"
      sha256 "5716f25495dab3458abf3abb1a62fe804309f723ca1d42800ab87b6163b0797e"

      def install
        bin.install "cfl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takymt/cflcli/releases/download/v0.2.1/cfl_0.2.1_linux_amd64.tar.gz"
      sha256 "880e349eac29cdbb40700600374df787a1961a23d4e3c1eeefa2255b00e1c335"
      def install
        bin.install "cfl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takymt/cflcli/releases/download/v0.2.1/cfl_0.2.1_linux_arm64.tar.gz"
      sha256 "f8e368107c8f889adf4cf21395d5af75ff6fcb5f29d6094f3c4750dc3404d38c"
      def install
        bin.install "cfl"
      end
    end
  end

  test do
    system "#{bin}/cfl", "--help"
  end
end
